<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Book More Services</name>
   <tag></tag>
   <elementGuidId>7299af5b-49eb-4b09-a5af-92b60828b8d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Box-sc-1fygfj3-0.Flex-sc-93g7hz-0.Button-sc-1jkjll9-0.Button-cpsnps-0.CtaButton-cc3ssq-0.esuPqS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95283818-1ecf-4da9-b4d0-45a2e250aa1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>STEPS.CART.BACK_TO_SHOPPING_BUTTON</value>
      <webElementGuid>31daa52b-8694-4bed-a7e7-4030555b1e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>black</value>
      <webElementGuid>db9f8bb5-2d1b-470e-8df4-14fd8b585669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c2de7d3-6eae-4f28-a5af-cfbabc29ac58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>display</name>
      <type>Main</type>
      <value>inline-flex</value>
      <webElementGuid>234031a9-ba59-49ab-8fb6-1fcda7e9edf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>regular</value>
      <webElementGuid>b1c0061d-abe3-4ce8-a852-fa56934304c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>ac92d904-312d-4661-9b5a-43aa6220a4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>50px</value>
      <webElementGuid>0bbfbbeb-1ed9-4506-bb9f-1303eb6e6306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Box-sc-1fygfj3-0 Flex-sc-93g7hz-0 Button-sc-1jkjll9-0 Button-cpsnps-0 CtaButton-cc3ssq-0 esuPqS</value>
      <webElementGuid>0c680654-4eb2-4783-a287-0a7887c040ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book More Services</value>
      <webElementGuid>d81361d7-0dfc-4731-b052-b610e5d5fb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-cartDetails&quot;)/div[2]/div[@class=&quot;Box-sc-1fygfj3-0 Flex-sc-93g7hz-0 CtaContainer-sc-1vh5v8c-0 dVXfpz&quot;]/div[@class=&quot;Box-sc-1fygfj3-0 Flex-sc-93g7hz-0 gaZOpW&quot;]/button[@class=&quot;Box-sc-1fygfj3-0 Flex-sc-93g7hz-0 Button-sc-1jkjll9-0 Button-cpsnps-0 CtaButton-cc3ssq-0 esuPqS&quot;]</value>
      <webElementGuid>dd740017-217b-4f09-9373-1843ee85311d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Arins SLiM INDiA/iframe_concat(id(, , commerce_cart_frame, ,_70d00f</value>
      <webElementGuid>b4a36129-7916-4b66-992f-272741232e6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>540a94c9-9463-4142-9dcb-f78107e99386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='step-cartDetails']/div[2]/div[3]/div/button[2]</value>
      <webElementGuid>475d0f95-3ac3-4403-af1e-5fe36abf7559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Booking'])[1]/following::button[1]</value>
      <webElementGuid>9d956c81-def6-47d3-b4ef-969a30b90654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::button[2]</value>
      <webElementGuid>9bfc42a2-1499-4160-8c10-980b1b1e7b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Book More Services']/parent::*</value>
      <webElementGuid>93428ddd-fa79-49bc-a271-49757d326279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>dcf84697-435c-42f1-9791-6dcbd589bc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Book More Services' or . = 'Book More Services')]</value>
      <webElementGuid>eba7bff3-e8e2-4caa-ad8b-174cc628eafe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
