<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , commerce_cart_frame, ,_70d00f</name>
   <tag></tag>
   <elementGuidId>f8247067-057f-4340-b3bf-005f6bcc1c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#commerce_cart_frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='commerce_cart_frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6d0ebde1-62cb-4226-9cc9-62111903d561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>52deae0c-56ab-4444-a25c-15f26e339b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>94b9e8cc-88e0-4e24-9110-b5c45309b132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>abd07564-1e01-448c-af43-8f1d2dd6b038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>IFRAME.CONTAINER</value>
      <webElementGuid>5bcf3c88-4097-40ce-bcee-b99159b8f129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment</value>
      <webElementGuid>8eda6ff5-e4e9-408f-8776-8b345de2ddb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>commerce_cart_frame</value>
      <webElementGuid>290edb5b-5dde-4c37-bb31-9dc559af1f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://arinslimindia.com/g/api/cart/cart?cartNotifyTimeout=5000&amp;websiteId=2daacd3a-c75f-4ffa-9385-2df643494012&amp;env=production&amp;cartUrl=https://arinslimindia.com/g/api/cart&amp;websiteUrl=https://arinslimindia.com</value>
      <webElementGuid>b486fafb-31a2-436c-b6d2-e40bfa414a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commerce_cart_frame&quot;)</value>
      <webElementGuid>1fbeb8f3-4e31-4927-a0ba-7ad7177424e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='commerce_cart_frame']</value>
      <webElementGuid>17d249e8-e47d-45a8-9267-0e8970b7aab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0ed2d6e6-eda1-4d1d-b7fc-1cae84c3b46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'commerce_cart_frame' and @src = 'https://arinslimindia.com/g/api/cart/cart?cartNotifyTimeout=5000&amp;websiteId=2daacd3a-c75f-4ffa-9385-2df643494012&amp;env=production&amp;cartUrl=https://arinslimindia.com/g/api/cart&amp;websiteUrl=https://arinslimindia.com']</value>
      <webElementGuid>2832b4f6-7726-4f6c-b17f-0edac1c7b27a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
