<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__customer-last-name</name>
   <tag></tag>
   <elementGuidId>efd2de8d-d70e-4f7f-b787-32cb2c4a9ad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer-last-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer-last-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58dcd79e-b479-4c8d-8f9c-635a5ff02d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>customer-last-name</value>
      <webElementGuid>4d5e8d9f-4705-4960-9d76-a3c093a826f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>ce3b0a77-e984-44c8-a60b-f83d7beac93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer-last-name</value>
      <webElementGuid>74aa14e4-0cd7-4dd5-a01e-c263254b60e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>5e53c63e-7789-438a-a2ca-e9a4a04af572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>186b4366-b157-4881-b347-f9553a53ee8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>1c8650a7-ffca-41cf-9a7c-fb68d3e7dc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>36px</value>
      <webElementGuid>6f209cbe-3ad7-4fc5-8ed5-2e3ed2daf73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Box-sc-1fygfj3-0 FieldBase-sc-1a5zvch-0 jYzgxj</value>
      <webElementGuid>9bd2e0ac-67a8-496a-9d98-c12e04656f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-last-name&quot;)</value>
      <webElementGuid>3bf85b5a-8c19-4af0-bf61-e751a004766b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Arins SLiM INDiA/iframe_concat(id(, , commerce_cart_frame, ,_70d00f</value>
      <webElementGuid>58dd49df-1e7a-4ffb-b207-bd91b2339af4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer-last-name']</value>
      <webElementGuid>cbdddc4b-91c6-4a1e-92a8-b76d8ff97860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='step-cartDetails']/div[2]/div[2]/form/div/div[2]/input</value>
      <webElementGuid>e1e613d0-5d42-4e42-b438-e162e3221006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>7a0d6591-1dc5-46e4-9fee-4d13038f318e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customer-last-name' and @type = 'text']</value>
      <webElementGuid>cd61b836-7334-4b16-ab72-ce0b380ce27c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
