<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__customer-first-name</name>
   <tag></tag>
   <elementGuidId>6f211022-0cfa-4f85-bc3f-61a5c2c86f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer-first-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer-first-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1effc21e-26d6-4ce6-b4ac-4782c2dd5559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>customer-first-name</value>
      <webElementGuid>4e7476fe-a9ad-4888-b515-2e2859b8f10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>52d5bfd4-1616-4d5a-b1ad-55b1aece76b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer-first-name</value>
      <webElementGuid>39e0e26a-19f2-4042-89a6-d92e3de9ee09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>19eb0593-c553-4ace-9911-22631d545ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d52a20f-1b19-4531-be30-177ff264ce9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d40779c5-50d4-4142-af21-ba2a18ac57d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>36px</value>
      <webElementGuid>a352d672-8966-40d6-ac3d-62db0ad9b964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Box-sc-1fygfj3-0 FieldBase-sc-1a5zvch-0 jYzgxj</value>
      <webElementGuid>e747fe3e-5fce-42a3-83f8-f763b3781cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-first-name&quot;)</value>
      <webElementGuid>1bc39b70-c79e-423f-834a-5af3d51bc0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Arins SLiM INDiA/iframe_concat(id(, , commerce_cart_frame, ,_70d00f</value>
      <webElementGuid>f861a9f2-f638-43a7-a091-19dd08f407c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer-first-name']</value>
      <webElementGuid>e5cdb043-603e-45cf-b3fa-b1e1ce188299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='step-cartDetails']/div[2]/div[2]/form/div/div/input</value>
      <webElementGuid>1ea0d34c-0574-4584-a6ef-ebb1791b86d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>53bed551-621b-43b1-aa23-8afb0abf3e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customer-first-name' and @type = 'text']</value>
      <webElementGuid>7dd40e1d-ac9c-4579-9738-f1ff409743d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
